### ISSUE TITLE
Shop 

### ISSUE THREAD

**Issue by aarvndhNG** [yf836760/CustomItemShop#2]
Can you make rank system and shop plugin without customitem

**Comment by aarvndhNG** [comment]
@yf836760

**Comment by yf836760** [comment]
Yeah， but as far as am concerned you can find what you want in https://www.bbstr.net/n/plugin/

**Comment by aarvndhNG** [comment]
Ok and you can the plugin language to English please

**Comment by aarvndhNG** [comment]
[5811_98d90ee005683a9a3b4e38a69d594647.zip](https://github.com/yf836760/CustomItemShop/files/10499665/5811_98d90ee005683a9a3b4e38a69d594647.zip)
This @yf836760 please sir

**Comment by yf836760** [comment]
鞭长莫及

**Comment by aarvndhNG** [comment]
Hi

**Comment by yf836760** [comment]
Hi

**Comment by aarvndhNG** [comment]
Can you add shop i mean can you separate this plugin into shop pls

**Comment by yf836760** [comment]
I have devised a plan to extract the 'CustomItem' from the plugin later this year. Thx for your support.

**Comment by aarvndhNG** [comment]
Mm np

**Comment by aarvndhNG** [comment]
Do r u rebuilding and making shop plugin separately

**Comment by yf836760** [comment]
Yes, only "custom item shop" will be left.

**Comment by aarvndhNG** [comment]
O thanks
